version: '3.8'
services:
  payload:
    image: "${TESTING_IMAGE}"
    environment:
      DATABASE_URI: '$${ secrets.DATABASE_URI }'
      DOCKERHUB_TOKEN: $${ secrets.DOCKERHUB_TOKEN }
      DOCKERHUB_USERNAME: $${ secrets.DOCKERHUB_USERNAME }
      NEXT_PUBLIC_MAPBOX_ACCESS_TOKEN: $${ secrets.NEXT_PUBLIC_MAPBOX_ACCESS_TOKEN }
      PAYLOAD_SECRET: $${ secrets.PAYLOAD_SECRET }
      NEXT_PRIVATE_DRAFT_SECRET: $${ secrets.NEXT_PRIVATE_DRAFT_SECRET }
      NEXT_PRIVATE_REVALIDATION_KEY: $${ secrets.NEXT_PRIVATE_REVALIDATION_KEY }
      PAYLOAD_PUBLIC_DRAFT_SECRET: $${ secrets.PAYLOAD_PUBLIC_DRAFT_SECRET }
      PAYLOAD_PUBLIC_SERVER_URL: '$${ secrets.PAYLOAD_PUBLIC_SERVER_URL }'
      PORT: $${ secrets.PORT }
      REVALIDATION_KEY: $${ secrets.REVALIDATION_KEY }
      NEXT_PUBLIC_SERVER_URL: '$${ secrets.NEXT_PUBLIC_SERVER_URL }'

  mongo:
    image: mongo:latest
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: "${TESTING_IMAGE}"
      ME_CONFIG_MONGODB_ADMINPASSWORD: "${TESTING_IMAGE}"
      ME_CONFIG_MONGODB_URL: 'mongodb+srv://${MONGODB_ADMINUSERNAME}:${MONGODB_ADMINPASSWORD}@sitatlas-cluster.3eew6oe.mongodb.net/payload_sandbox'
    volumes:
      - ./infra:/healthchecks
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo 'mongodb+srv://${MONGODB_ADMINUSERNAME}:${MONGODB_ADMINPASSWORD}@sitatlas-cluster.3eew6oe.mongodb.net/payload_sandbox' --quiet
      interval: 10s
  sut:
    image: "${TESTING_IMAGE}"
    depends_on:
      payload:
        condition: service_started
      mongo:
        condition: service_healthy
    command: exit 1
