version: '3.8'

services:
  payload:
    build:
      context: .
      dockerfile: infra/Dockerfile.dev
    image: node:20-alpine
    ports:
      - '3000:3000'
    volumes:
      - ./:/home/node/app
      - node_modules:/home/node/app/node_modules
      - ./.next:/app/.next
    restart: unless-stopped
    working_dir: /home/node/app/
    depends_on:
      - mongo
    env_file:
      - .env
    networks:
    - payload_network

  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
    command:
      - --storageEngine=wiredTiger
    volumes:
      - data:/data/db
    logging:
      driver: local
    networks:
      - payload_network
      

volumes:
  data:
  node_modules:
  next:
networks:
  payload_network: