version: '3.8'
services:
  payload:
    image: node:20-alpine
    container_name: payload-dev
    build:
      context: .
      dockerfile: infra/docker/Dockerfile.dev
    ports:
      - '3000:3000'
    volumes:
      - ./:/home/node/app
      - node_modules:/home/node/app/node_modules
      - ./.next:/app/.next
    working_dir: /home/node/app/
    depends_on:
      - mongo
    env_file:
      - .env.docker
    networks:
      - payload_network
  mongo:
    image: mongo:4.4.27
    container_name: mongo-dev
    ports:
      - '27017:27017'
    command:
      - --storageEngine=wiredTiger
    volumes:
      - data:/data/db
    logging:
      driver: local
    networks:
      - payload_network
volumes:
  data:
  node_modules:
  next:
networks:
  payload_network: