FROM node:20-alpine as base

FROM base as builder

WORKDIR /home/node/app
ENV PATH=/home/node/app/node_modules/.bin:$PATH
COPY package*.json ./

RUN npm install --legacy-peer-deps && npm cache clean --force

COPY . .

EXPOSE 3000

CMD ["npm", "run", "dev"]
