FROM node:20-alpine as base

FROM base as builder

WORKDIR /home/node/app
COPY package*.json ./

COPY . .
RUN yarn install
RUN --mount=type=secret,id=PAYLOAD_SECRET,required  \
  --mount=type=secret,id=DATABASE_URI,required  \
  --mount=type=secret,id=DOCKERHUB_TOKEN,required  \
  --mount=type=secret,id=DOCKERHUB_USERNAME,required  \
  --mount=type=secret,id=NEXT_PUBLIC_MAPBOX_ACCESS_TOKEN,required  \
  --mount=type=secret,id=NEXT_PRIVATE_DRAFT_SECRET,required  \
  --mount=type=secret,id=NEXT_PRIVATE_REVALIDATION_KEY,required  \
  --mount=type=secret,id=NEXT_PUBLIC_SERVER_URL,required  \
  --mount=type=secret,id=PAYLOAD_PUBLIC_DRAFT_SECRET,required  \
  --mount=type=secret,id=PAYLOAD_PUBLIC_SERVER_URL,required  \
  --mount=type=secret,id=PORT,required  \
  --mount=type=secret,id=REVALIDATION_KEY,required  \
  --mount=type=secret,id=OPENAI_API_KEY,required  \
  --mount=type=secret,id=ASSISTANT_API_KEY,required  \
   export PAYLOAD_SECRET=$(cat /run/secrets/PAYLOAD_SECRET) && \
   export DATABASE_URI=$(cat /run/secrets/DATABASE_URI) && \
   export DOCKERHUB_TOKEN=$(cat /run/secrets/DOCKERHUB_TOKEN) && \
   export DOCKERHUB_USERNAME=$(cat /run/secrets/DOCKERHUB_USERNAME) && \
   export NEXT_PUBLIC_MAPBOX_ACCESS_TOKEN=$(cat /run/secrets/NEXT_PUBLIC_MAPBOX_ACCESS_TOKEN) && \
   export NEXT_PRIVATE_DRAFT_SECRET=$(cat /run/secrets/NEXT_PRIVATE_DRAFT_SECRET) && \
   export NEXT_PRIVATE_REVALIDATION_KEY=$(cat /run/secrets/NEXT_PRIVATE_REVALIDATION_KEY) && \
   export NEXT_PUBLIC_SERVER_URL=$(cat /run/secrets/NEXT_PUBLIC_SERVER_URL) && \
   export PAYLOAD_PUBLIC_DRAFT_SECRET=$(cat /run/secrets/PAYLOAD_PUBLIC_DRAFT_SECRET) && \
   export PAYLOAD_PUBLIC_SERVER_URL=$(cat /run/secrets/PAYLOAD_PUBLIC_SERVER_URL) && \
   export PORT=$(cat /run/secrets/PORT) && \
   export REVALIDATION_KEY=$(cat /run/secrets/REVALIDATION_KEY) && \
   export OPENAI_API_KEY=$(cat /run/secrets/OPENAI_API_KEY) && \
   export ASSISTANT_API_KEY=$(cat /run/secrets/ASSISTANT_API_KEY) && \
    yarn build

FROM base as runtime

ENV NODE_ENV=production
ENV PAYLOAD_CONFIG_PATH=dist/payload/payload.config.js

WORKDIR /home/node/app
COPY package*.json  ./

RUN yarn install --production
COPY --from=builder /home/node/app/dist ./dist
COPY --from=builder /home/node/app/build ./build
COPY --from=builder /home/node/app/.next ./.next

EXPOSE 3000

CMD ["node", "dist/server.js"]