name: Continous Deplyoment - Docker

on:
    workflow_run:
        workflows: ["Continuous Integration"]
        branches: [release]
        types:
            - completed
    pull_request:
        types: [closed]
        branches:
            - release
    push:
        branches:
            - '*'

jobs:
    deploy:
        runs-on: ubuntu-20.04
        steps:
            - 
                name: Check git repo
                uses: actions/checkout@v2
                # Runs a set of commands using the runners shell
            - 
                name: Run a multi-line script
                run: |
                    mkdir ../build
                    cp docker-compose.prod.yml ../build
                    cp infra/docker/Dockerfile.prod ../build
                    tar -cvf deploy.tar ../build/
            - 
                name: SCP docker-compose.prod to Server
                uses: appleboy/scp-action@master
                with:
                    host: ${{ secrets.DO_PRODUCTION_HOST }}
                    username: ${{ secrets.DO_PRODUCTION_USERNAME }}
                    # password: ${{ secrets.DO_PRODUCTION_PASSWORD }}
                    key: ${{ secrets.DO_PRODUCTION_PRIVATE_KEY }}
                    source: "deploy.tar"
                    target: "/home/sitatlas/home/app/sitatlas/"
            - 
                name: SSH and Deploy
                uses: appleboy/ssh-action@master
                with:
                    host: ${{ secrets.DO_PRODUCTION_HOST }}
                    username: ${{ secrets.DO_PRODUCTION_USERNAME }}
                    # password: ${{ secrets.DO_PRODUCTION_PASSWORD }}
                    key: ${{ secrets.DO_PRODUCTION_PRIVATE_KEY }}
                    script: |
                        echo "Unzip and Move Files"
                        cd /home/sitatlas/home/app/sitatlas/
                        tar -xf deploy.tar
                        cp build/docker-compose.prod.yml ./
                        cp build/Dockerfile.prod ./infra/docker/

                        echo "Running Docker Compose"
                        docker-compose -f docker-compose.prod pull
                        docker-compose -f docker-compose.prod down
                        docker-compose -f docker-compose.prod up -d

                        echo "Restarting NGINX"
                        sudo systemctl restart nginx
                
