name: Continous Deplyoment

on:
    workflow_run:
        workflows: ["Continous Integration"]
        branches: ["*"]
        types:
            - completed
    pull_request:
        types: [closed]
        branches:
            - master
    # push:
    #     branches:
    #         - '*'

jobs:
    deploy:
        runs-on: ubuntu-20.04
        steps:
            - 
                name: Check git repo
                uses: actions/checkout@v2
                # Runs a set of commands using the runners shell
            - 
                name: Run a multi-line script
                run: |
                    mkdir ../build
                    cp docker-compose.prod.yml ../build
                    cp infra/docker/Dockerfile.prod ../build
                    tar -cvf deploy.tar ../build/
            - 
                name: SCP docker-compose.prod to Server
                uses: appleboy/scp-action@master
                with:
                    host: ${{ secrets.DO_PRODUCTION_HOST }}
                    username: ${{ secrets.DO_PRODUCTION_USERNAME }}
                    password: ${{ secrets.DO_PRODUCTION_PASSWORD }}
                    # key: ${{ secrets.DO_PRODUCTION_PRIVATE_KEY }}
                    source: "deploy.tar"
                    target: "/home/sitatlas/home/app/sitatlas/"
            -
                name: Login to Docker Hub
                uses: docker/login-action@v3
                with:
                    username: ${{ secrets.DOCKERHUB_USERNAME }}
                    password: ${{ secrets.DOCKERHUB_TOKEN }}
            - 
                name: SSH and Deploy
                uses: appleboy/ssh-action@master
                with:
                    host: ${{ secrets.DO_PRODUCTION_HOST }}
                    username: ${{ secrets.DO_PRODUCTION_USERNAME }}
                    password: ${{ secrets.DO_PRODUCTION_PASSWORD }}
                    # key: ${{ secrets.DO_PRODUCTION_PRIVATE_KEY }}
                    script: |
                        echo "Unzip and Move Files"
                        cd /home/sitatlas/home/app/sitatlas/
                        tar -xf deploy.tar
                        cp -f build/docker-compose.prod.yml ./
                        cp -f build/Dockerfile.prod ./infra/docker/
                        rm -rf build/
                        rm -rf deploy.tar

                        echo "Running Docker Compose"
                        docker compose -f docker-compose.prod.yml pull
                        docker compose -f docker-compose.prod.yml down
                        docker compose -f docker-compose.prod.yml up -d

                        echo "Restarting NGINX"
                        echo ${{ secrets.DO_PRODUCTION_PASSWORD }}sudo systemctl restart nginx
                
