version: '3.8'
services:
  payload:
    image: node:20-alpine
    container_name: payload
    ports:
      - '3000:3000'
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    working_dir: /home/node/app/
    command: sh -c "yarn install && yarn dev"
    depends_on:
      - mongo
    env_file:
      - .env.docker
    networks:
    - payload_network
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - '27017:27017'
    command:
      - --storageEngine=wiredTiger
    volumes:
      - data:/data/db
    logging:
      driver: local
    networks:
      - payload_network
  nginx:
    image: nginx:latest
    build: 
      context: .
      dockerfile: infra/docker/Dockerfile.nginx
    container_name: nginx
    tty: true
    ports: 
      - '8000:80'
    networks: 
      - payload_network
    depends_on:
       - payload
       - mongo
volumes:
  data:
  node_modules:
networks:
  payload_network: